### PR TITLE
Credit card fraud detection

### PR DESCRIPTION
**Pull request by pbuggaveeti28**

### CODE REVIEW

**Comment by pbuggaveeti28** [comment]
Can you check once and merge

**Comment by pbuggaveeti28** [comment]
@Brillianttyagi Can u review the PR and merge

**Comment by deeptheengineer** [comment]
it is not a small script it is full program can you try one again

**Comment by pbuggaveeti28** [comment]
What type of python scripts can I add?  Any kind of algorithms?

**Comment by skynextindia** [comment]
Hola guys,is that python and tf based?

**Comment by deeptheengineer** [comment]
python based for controlling os

**Pull request closed without merging**
