### PR TITLE
Added file VirusTotalScanner.py. Renamed email.py to email-sender.py

### PR DESCRIPTION
**Pull request by shivamsn97**
### VirusTotalScanner.py scans a file for virus online using VirusTotal API. 

Usage:
`python VirusTotalScanner.py /path/to/yourfile`

Installation:
```shell
pip install colorama
pip install vt-py
```

Login to https://www.virustotal.com/gui/, create an account, get your API key, and Paste that key in the API_KEY variable in VirusTotalScanner.py.

For a more detailed solution, and adding this script to your context menu, check out the main repo at https://github.com/shivamsn97/ScanIt

### Renamed email.py to email-sender.py
Because it was conflicting with the python inbuilt module, email.

### CODE REVIEW

**Comment by deeptheengineer** [comment]
Can you give me a snapshot of running program

**Comment by shivamsn97** [comment]
> 
> 
> Can you give me a snapshot of running program

Sure, Check it out.

image

**Comment by shivamsn97** [comment]
Any update sir?

**Comment by deeptheengineer** [comment]
good luck!

**Pull request merged**
